const STATUS = {
  statusLabel: {
    0: '未提交',
    1: '待审核',
    2: '已审核',
    3: '申请驳回待修改',
    9: '审核不通过',

    10: '未提交',
    11: '待审核',
    12: '审核中',
    13: '申请驳回待修改',
    19: '审核不通过',

    20: '未提交',
    21: '待审核',
    22: '审核中',
    23: '申请驳回待修改',
    29: '审核不通过',

    30: '未提交',
    31: '待审核',
    32: '审核中',
    33: '申请驳回待修改',
    39: '审核不通过',

    40: '未提交',
    41: '待审核',
    42: '审核中',
    43: '申请驳回待修改',
    49: '审核不通过',

    50: '未提交',
    51: '待审核',
    52: '已审核',
    53: '申请驳回待修改',
    59: '审核不通过',

    60: '未提交',
    61: '待审核',
    62: '已审核',
    63: '申请驳回待修改',
    69: '审核不通过',

    70: '未提交',
    71: '待审核',
    72: '已审核',
    73: '申请驳回待修改',
    79: '审核不通过',

    81: '待审核',
    82: '已审核',
    89: '审核不通过',
  },
  statusMap: {
    0: 'greyStatus',
    1: 'yellowStatus',
    2: 'greenStatus',
    3: 'greyStatus',
    9: 'redStatus',

    10: 'greyStatus',
    11: 'yellowStatus',
    12: 'greenStatus',
    13: 'greyStatus',
    19: 'redStatus',

    20: 'greyStatus',
    21: 'yellowStatus',
    22: 'greenStatus',
    23: 'greyStatus',
    29: 'redStatus',

    30: 'greyStatus',
    31: 'yellowStatus',
    32: 'greenStatus',
    33: 'greyStatus',
    39: 'redStatus',

    40: 'greyStatus',
    41: 'yellowStatus',
    42: 'greenStatus',
    43: 'greyStatus',
    49: 'redStatus',

    50: 'greyStatus',
    51: 'yellowStatus',
    52: 'greenStatus',
    53: 'greyStatus',
    59: 'redStatus',

    60: 'greyStatus',
    61: 'yellowStatus',
    62: 'greenStatus',
    63: 'greyStatus',
    69: 'redStatus',

    70: 'greyStatus',
    71: 'yellowStatus',
    72: 'greenStatus',
    73: 'greyStatus',
    79: 'redStatus',
  },
  statusColorMap: {
    0: 'greyStatus',
    1: 'yellowStatus',
    2: 'greenStatus',
    3: 'greyStatus',
    9: 'redStatus',

    10: 'greyStatus',
    11: 'yellowStatus',
    12: 'greenStatus',
    13: 'greyStatus',
    19: 'redStatus',

    20: 'greyStatus',
    21: 'yellowStatus',
    22: 'greenStatus',
    23: 'greyStatus',
    29: 'redStatus',

    30: 'greyStatus',
    31: 'yellowStatus',
    32: 'greenStatus',
    33: 'greyStatus',
    39: 'redStatus',

    40: 'greyStatus',
    41: 'yellowStatus',
    42: 'greenStatus',
    43: 'greyStatus',
    49: 'redStatus',

    50: 'greyStatus',
    51: 'yellowStatus',
    52: 'greenStatus',
    53: 'greyStatus',
    59: 'redStatus',

    60: 'greyStatus',
    61: 'yellowStatus',
    62: 'greenStatus',
    63: 'greyStatus',
    69: 'redStatus',

    70: 'greyStatus',
    71: 'yellowStatus',
    72: 'greenStatus',
    73: 'greyStatus',
    79: 'redStatus',

    81: 'yellowStatus',
    82: 'greenStatus',
    89: 'redStatus',
  },
};
export default STATUS;
